server.port=3888

spring.application.name=config-server
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config
spring.cloud.config.server.git.default-label=main

eureka.client.service-url.defaultZone=http://localhost:3761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info
