server.port=3761
server.address=0.0.0.0

spring.application.name=discovery-server

eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.server.enable-self-preservation=false
eureka.server.renewal-percent-threshold=0.49
eureka.server.eviction-interval-timer-in-ms=5000

management.endpoints.web.exposure.include=health,info
